index:
    path: /
    controller: App\Controller\index::home
create:
    path: /create
    controller: App\Controller\MsgController::index
reply:
    path: /reply
    controller: App\Controller\ReplyController::index
delete:
    path: /delete
    controller: App\Controller\DeleteController::index
replydelete:
    path: /replydelete
    controller: App\Controller\ReplydeleteController::index
write:
    path: /write
    controller: App\Controller\WriteController::index
replywrite:
    path: /replywrite
    controller: App\Controller\ReplywriteController::index